# Generated by Django 6.0.6 on 2026-06-28 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_google_id_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('template_path', models.CharField(help_text="Path relative to TEMPLATES dirs, e.g. 'themes/academic-light/index.html'", max_length=255)),
                ('preview_image', models.CharField(blank=True, max_length=255)),
                ('palette', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('academic_title', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True, help_text='Use double newlines for paragraphs. Wrap emphasis in **bold**.')),
                ('current_status', models.CharField(blank=True, help_text="e.g. 'On sabbatical at ETH, Spring 2026'", max_length=140)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('years_teaching', models.PositiveIntegerField(blank=True, null=True)),
                ('citation_count', models.PositiveIntegerField(blank=True, null=True)),
                ('students_supervised', models.PositiveIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.user')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolios.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text="e.g. 'Ph.D.', 'M.Sc.', 'B.Sc.'", max_length=100)),
                ('field_of_study', models.CharField(blank=True, help_text="e.g. 'in Computer Science'", max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, help_text='Leave blank if ongoing', null=True)),
                ('description', models.TextField(blank=True, help_text='Dissertation title, advisor, concentration, minor...')),
                ('honor', models.CharField(blank=True, help_text='Award badge (optional)', max_length=100)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='portfolios.profile')),
            ],
            options={
                'verbose_name_plural': 'Education entries',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('link_type', models.CharField(choices=[('email', 'Email'), ('location', 'Location'), ('phone', 'Phone'), ('clock', 'Office Hours'), ('scholar', 'Google Scholar'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('orcid', 'ORCID'), ('website', 'Website'), ('link', 'Other Link')], default='link', max_length=20)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='portfolios.profile')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pdf_link', models.TextField(blank=True)),
                ('github_link', models.CharField(blank=True, max_length=500)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='portfolios.profile')),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='ResearchInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_interests', to='portfolios.profile')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=45)),
                ('description', models.TextField(blank=True)),
                ('syllabus_link', models.URLField(blank=True, null=True)),
                ('teachingscol', models.CharField(blank=True, max_length=45)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachings', to='portfolios.profile')),
            ],
        ),
    ]