# Generated by Django 5.2.14 on 2026-07-02 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_google_id_user_profile_picture'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('template_path', models.CharField(help_text="Path relative to TEMPLATES dirs, e.g. 'themes/academic-light/index.html'", max_length=255)),
                ('preview_image', models.CharField(blank=True, max_length=255)),
                ('palette', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='media',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='page',
            name='profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='profile_image',
        ),
        migrations.RenameField(
            model_name='teaching',
            old_name='teachingscol',
            new_name='semester',
        ),
        migrations.AddField(
            model_name='profile',
            name='citation_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_status',
            field=models.CharField(blank=True, help_text="e.g. 'On sabbatical at ETH, Spring 2026'", max_length=140),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='research_interests',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_template',
            field=models.CharField(blank=True, choices=[('classic-scholar', 'Classic Scholar'), ('modern-dark', 'Modern Dark'), ('minimalist-lab', 'Minimalist Lab'), ('executive-academic', 'Executive Academic')], default='classic-scholar', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='students_supervised',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_teaching',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Use double newlines for paragraphs. Wrap emphasis in **bold**.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='field_of_study',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.user'),
        ),
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('link_type', models.CharField(choices=[('email', 'Email'), ('location', 'Location'), ('phone', 'Phone'), ('clock', 'Office Hours'), ('scholar', 'Google Scholar'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('orcid', 'ORCID'), ('website', 'Website'), ('link', 'Other Link')], default='link', max_length=20)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='portfolios.profile')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text="e.g. 'Ph.D.', 'M.Sc.', 'B.Sc.'", max_length=100)),
                ('field_of_study', models.CharField(blank=True, help_text="e.g. 'in Computer Science'", max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, help_text='Leave blank if ongoing', null=True)),
                ('description', models.TextField(blank=True, help_text='Dissertation title, advisor, concentration, minor...')),
                ('honor', models.CharField(blank=True, help_text='Award badge (optional)', max_length=100)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='portfolios.profile')),
            ],
            options={
                'verbose_name_plural': 'Education entries',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='ResearchInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_interests_entries', to='portfolios.profile')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolios.theme'),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
