# Generated by Django 6.0.6 on 2026-07-12 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_profile_onboarding_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teaching',
            options={'ordering': ['order_index']},
        ),
        migrations.AddField(
            model_name='teaching',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teaching',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teaching',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
