# Generated by Django 6.0.6 on 2026-06-30 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_repair_profile_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_scholar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='research_gate',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchinterest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_interests_entries', to='portfolios.profile'),
        ),
    ]
